<?php

declare(strict_types=1);

/**
 * This file is part of the DEBs-to-SQL package
 *
 * https://github.com/VitexSoftware/DEBs-to-SQL
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\DebToSQL;

use DebToSQL\Deb;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-09-27 at 22:16:49.
 */
class DebTest extends \PHPUnit\Framework\TestCase
{
    protected Deb $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Deb();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \DebToSQL\Deb::getIcon
     */
    public function testgetIcon(): void
    {
        $this->assertEquals('img/deb-package.png', $this->object->getIcon('ldd2debs'));
    }

    /**
     * @covers \DebToSQL\Deb::getIconUrl
     */
    public function testgetIconUrl(): void
    {
        $this->assertEquals('', $this->object->getIconUrl('ldd2debs'));
    }
}
