<?php

declare(strict_types=1);

/**
 * This file is part of the DEBs-to-SQL package
 *
 * https://github.com/VitexSoftware/DEBs-to-SQL
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\DebToSQL;

use DebToSQL\Files;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-09-27 at 22:19:17.
 */
class FilesTest extends \PHPUnit\Framework\TestCase
{
    protected Files $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Files();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \DebToSQL\Files::indexPackageContents
     *
     * @todo   Implement testindexPackageContents().
     */
    public function testindexPackageContents(): void
    {
        $this->assertEquals('', $this->object->indexPackageContents());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Files::getPackageContents
     *
     * @todo   Implement testgetPackageContents().
     */
    public function testgetPackageContents(): void
    {
        $this->assertEquals('', $this->object->getPackageContents());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
