<?php

namespace Test\DebToSQL;

use DebToSQL\Files;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-09-27 at 22:19:17.
 */
class FilesTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Files
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Files();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers DebToSQL\Files::indexPackageContents
     * @todo   Implement testindexPackageContents().
     */
    public function testindexPackageContents() {
        $this->assertEquals('', $this->object->indexPackageContents());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers DebToSQL\Files::getPackageContents
     * @todo   Implement testgetPackageContents().
     */
    public function testgetPackageContents() {
        $this->assertEquals('', $this->object->getPackageContents());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
