<?php

namespace Test\DebToSQL;

use DebToSQL\Packages;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-09-27 at 22:16:51.
 */
class PackagesTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Packages
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Packages();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }
}
