<?php

declare(strict_types=1);

/**
 * This file is part of the DEBs-to-SQL package
 *
 * https://github.com/VitexSoftware/DEBs-to-SQL
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\DebToSQL;

use DebToSQL\Repository;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-09-27 at 22:26:27.
 */
class RepositoryTest extends \PHPUnit\Framework\TestCase
{
    protected Repository $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Repository();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \DebToSQL\Repository::parseDists
     *
     * @todo   Implement testparseDists().
     */
    public function testparseDists(): void
    {
        $this->assertEquals('', $this->object->parseDists());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::parseDist
     *
     * @todo   Implement testparseDist().
     */
    public function testparseDist(): void
    {
        $this->assertEquals('', $this->object->parseDist());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::parseSuites
     *
     * @todo   Implement testparseSuites().
     */
    public function testparseSuites(): void
    {
        $this->assertEquals('', $this->object->parseSuites());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::parseArchs
     *
     * @todo   Implement testparseArchs().
     */
    public function testparseArchs(): void
    {
        $this->assertEquals('', $this->object->parseArchs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::onlyKnownColumns
     *
     * @todo   Implement testonlyKnownColumns().
     */
    public function testonlyKnownColumns(): void
    {
        $this->assertEquals('', $this->object->onlyKnownColumns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::readpackages
     *
     * @todo   Implement testreadpackages().
     */
    public function testreadpackages(): void
    {
        $this->assertEquals('', $this->object->readpackages());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::saveAllToSQL
     *
     * @todo   Implement testsaveAllToSQL().
     */
    public function testsaveAllToSQL(): void
    {
        $this->assertEquals('', $this->object->saveAllToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::updatePresenceStatus
     *
     * @todo   Implement testupdatePresenceStatus().
     */
    public function testupdatePresenceStatus(): void
    {
        $this->assertEquals('', $this->object->updatePresenceStatus());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \DebToSQL\Repository::indexPackageContents
     *
     * @todo   Implement testindexPackageContents().
     */
    public function testindexPackageContents(): void
    {
        $this->assertEquals('', $this->object->indexPackageContents());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
