#!/bin/sh
# postinst script for debs2sql
set -e

case "$1" in
    configure)
        echo "edit /etc/debs2sql/.env and run debs2sql-phinx to prepare database";
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

echo TIP: run debs2sql-phinx

#DEBHELPER#

exit 0
