#!/bin/sh
# postinst script for debs2sql
set -e

. /usr/share/debconf/confmodule

db_get composer/WEB_USER
WEBUSER=$RET
mkdir -p /var/lib/debs2sql /var/lib/composer
chown $WEBUSER /var/lib/debs2sql /var/lib/composer -R
echo '{}' > /usr/lib/debs2sql/composer.lock
chown $WEBUSER /usr/lib/debs2sql/composer.lock
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o install -d /usr/lib/debs2sql/'


. /usr/share/debconf/confmodule


case "$1" in
    configure)
        echo "edit /etc/debs2sql/.env and run debs2sql-phinx to prepare database";
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac




#DEBHELPER#

exit 0
