#!/bin/sh
# postinst script for debs2sql
set -e

. /usr/share/debconf/confmodule




case "$1" in
    configure)

	db_get composer/WEB_USER || true
	WEB_USER=$(echo $RET | awk -F: '{print $1}')
	WEB_GROUP=$(echo $RET | awk -F: '{print $2}')

	id -u $WEB_USER &>/dev/null || useradd $WEB_USER

	if [ -z $WEB_GROUP ] ; then
	    chown $WEB_USER /var/lib/composer/ /usr/lib/debs2sql -Rv
	else
	    id -g $WEB_GROUP &>/dev/null || groupadd $WEB_USER
    	    chown $WEB_USER:$WEB_GROUP /var/lib/composer/ /usr/lib/debs2sql -Rv
	fi

	echo '{}' > /usr/lib/debs2sql/composer.lock
	chown $WEB_USER /usr/lib/debs2sql/composer.lock
	su - $WEB_USER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o install -d /usr/lib/debs2sql/'



        echo "edit /etc/debs2sql/.env and run debs2sql-phinx to prepare database";
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac




#DEBHELPER#

exit 0
